### ISSUE TITLE
[FR] "srt_caller"/"srt_listener" should be replaced by "srt_source"/"srt_destination"

### ISSUE THREAD

**Issue by Windrow14** [Haivision/srt-prometheus-exporter#12]
#### Motivation

"Caller" and "listener" have special meaning in SRT. They are for different call modes, or roles in an SRT connection establishment.  
But here in srt-exporter, in the samples and filter modes, what matters is whether the SRT user sends out data or receives in data.  

To make less confusion, these words shold be replaced.

#### Feature description

According to "Secure Reliable Transport Protocol Deployment Guide", module "Introduction to SRT", chapter "Basic SRT concepts", "source" and "destination" are more proper words to be used here. 

srt_caller -> srt_source  
srt_listener -> srt_destination  

#### Implementation considerations

Double check if there is any conflict with new names.

**Comment by fujitatomoya** [comment]
actually this breaks the sample application build, i will update the sample/Makefile accordingly.

**Comment by fujitatomoya** [comment]
@Windrow14 why reopening this? is there any specific issue related to this one?

**Comment by Windrow14** [comment]
> @Windrow14 why reopening this? is there any specific issue related to this one?

@fujitatomoya Hmmm, I thought you agreed with this...  
https://github.com/Haivision/srt-prometheus-exporter/pull/16#discussion_r1185633454

**Comment by fujitatomoya** [comment]
I believe that those are already addressed, it always nice to check, so if you are willing to check the current code. that would be appreciated.

**Comment by Windrow14** [comment]
https://github.com/Haivision/srt-prometheus-exporter/pull/18
