### ISSUE TITLE
[FR] Coding Style Guide Documentation

### ISSUE THREAD

**Issue by fujitatomoya** [Haivision/srt-prometheus-exporter#20]
#### Motivation

Coding Style should be provided to accept the PR as guideline.

#### Feature description

We can refer to [Google C++ Style Guideline](https://google.github.io/styleguide/cppguide.html), and if necessary we can define our own policy and rules.

#### Implementation considerations

Provide coding style guideline on top page.

**Comment by Windrow14** [comment]
We may align with `Haivision/srt`'s code style if it has a more clear one someday.

https://github.com/Haivision/srt/blob/master/CONTRIBUTING.md#code-style  
https://github.com/Haivision/srt/blob/master/docs/dev/developers-guide.md#coding-rules

**Comment by fujitatomoya** [comment]
closing in favor of https://github.com/Haivision/srt-prometheus-exporter/pull/22
