### ISSUE TITLE
[FR] Coding style checker and workflow integration

### ISSUE THREAD

**Issue by fujitatomoya** [Haivision/srt-prometheus-exporter#21]
#### Motivation

follow up of https://github.com/Haivision/srt-prometheus-exporter/issues/20.
coding style needs to be checked by every single PR and commits to make sure incoming PRs are compatible with current development policy.

#### Feature description

We can rely on [cpplint](https://github.com/cpplint/cpplint), and integrate it to github workflow.

**Comment by Windrow14** [comment]
Commands to be added in the pipeline:
```
pip install cpplint
find -iname *.h | xargs cpplint
find -iname *.c | xargs cpplint
find -iname *.hpp | xargs cpplint
find -iname *.cpp | xargs cpplint
```
However, `cpplint` is just a static code checker. It does not modify code automatically by itself. We need to modify code according to its advice manually.

**Comment by Windrow14** [comment]
I have a problem.
`Cpplint` complains about `Lines should be <= 80 characters long  [whitespace/line_length] [2]`. I can resolve it by cutting the line in the middle, but there seems no standard for where to cut the line and how many white space we should add at the front of the new line or where to align with.

For example:
```
### Line too long:
        if (SRT_INVALID_SOCK != srt_connect(srtsock, (const struct sockaddr *)&addr, sa_len)) {
### solution 1
        if (SRT_INVALID_SOCK != srt_connect(srtsock,
                                (const struct sockaddr *)&addr, sa_len)) {
### solution 2
        if (SRT_INVALID_SOCK != srt_connect(srtsock,
                                            (const struct sockaddr *)&addr, sa_len)) {
### solution 3
        if (SRT_INVALID_SOCK !=
            srt_connect(srtsock, (const struct sockaddr *)&addr, sa_len)) {

...
```
There are hundreds of solutions can make `cpplint` shut up, but most of them looks even ugly than before.

**Comment by Windrow14** [comment]
> I have a problem. `Cpplint` complains about `Lines should be <= 80 characters long [whitespace/line_length] [2]`. I can resolve it by cutting the line in the middle, but there seems no standard for where to cut the line and how many white space we should add at the front of the new line or where to align with.
> 
> For example:
> 
> ```
> ### Line too long:
>         if (SRT_INVALID_SOCK != srt_connect(srtsock, (const struct sockaddr *)&addr, sa_len)) {
> ### solution 1
>         if (SRT_INVALID_SOCK != srt_connect(srtsock,
>                                 (const struct sockaddr *)&addr, sa_len)) {
> ### solution 2
>         if (SRT_INVALID_SOCK != srt_connect(srtsock,
>                                             (const struct sockaddr *)&addr, sa_len)) {
> ### solution 3
>         if (SRT_INVALID_SOCK !=
>             srt_connect(srtsock, (const struct sockaddr *)&addr, sa_len)) {
> 
> ...
> ```
> 
> There are hundreds of solutions can make `cpplint` silent, but most of them looks even ugly than before...

There is a standard about function calling and arguments here: https://google.github.io/styleguide/cppguide.html#Function_Calls

**Comment by Windrow14** [comment]
I'd like to neglect some warnings from `cpplint`, such as: `Do not use namespace using-directives. Use using-declarations instead. [build/namespaces] [5]`, `<mutex> is an unapproved C++11 header. [build/c++11] [5]`, and some warnings related to`SRT_DATA_MAP_INITIALIZER`

**Comment by fujitatomoya** [comment]
> However, cpplint is just a static code checker. It does not modify code automatically by itself. We need to modify code according to its advice manually.

I think that is developer's responsibility. Until workflow with cpplint green light, we will not merge the PR.

> There are hundreds of solutions can make cpplint silent, but most of them looks even ugly than before...

if it does not work with cpplint, we can use `// NOLINT` with justification.

**Comment by fujitatomoya** [comment]
closing in favor of https://github.com/Haivision/srt-prometheus-exporter/pull/22
