### ISSUE TITLE
the CMAKE issue

### ISSUE THREAD

**Issue by SeanOntheWay** [Haivision/srt-prometheus-exporter#6]
I'm sorry it maybe a stupid question..I tried to build the project，when I do:
`cmake .. -DBUILD_SHARED_LIBS=ON`
It errors like this:
`CMake Error: The source directory "/Promethus/srt-prometheus-exporter" does not appear to contain CMakeLists.txt.`
so maybe the source misses a file named"CMakeLists.txt"?

**Comment by Windrow14** [comment]
Currently, `cmake` is not supported. We are using `Makefile` and `g++` now. You can use `make` command if you have `g++` installed in your environment.

**Comment by SeanOntheWay** [comment]
Appreciate！
